name: Deploy FrontEnd to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Static Site to S3 Bucket
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete

      # - name: Deploy to S3
      #   uses: aws-actions/s3-sync@v2
      #   with:
      #     bucket: ${{ secrets.S3_BUCKET_NAME }}
      #     region: ${{ secrets.AWS_REGION }}
      #     source-dir: build
